### ISSUE TITLE
This is great! Just what I was looking for

### ISSUE THREAD

**Issue by gdmcdonald** [macmillancontentscience/bespoke#5]
No issue, just thank you! 

I was helpfully referred here by @simonpcouch

**Comment by jonthegeek** [comment]
Thank you! I knocked this out for a specific use-case and to demonstrate the concept of a tidymodels package at my former job, and haven't thought that much about it since leaving.

Have you used it? Did it work how you hoped? What else would you like to see, if anything?

I'll try to come back to this at some point and clean it up for CRAN submission, particularly if you found it helpful!

**Comment by simonpcouch** [comment]
I gave it a go yesterday while answering [Gordon's StackOverflow question](https://stackoverflow.com/questions/78192500/how-to-specify-a-dummy-model-heuristic-rule-as-a-model-in-tidymodels/78193361#78193361)! It's a super useful tool and I'm grateful you put the time in to put it together.🙂
